sudo: false
language: python
cache: pip
matrix:
    include:
        # Linux
        - python: 2.7
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - python: 3.7
          dist: xenial
          sudo: true
        - python: pypy
        - python: pypy3
        # OSX
        - language: generic
          os: osx
          env: PYVER=py27
        - language: generic
          os: osx
          env: PYVER=py36
install:
    - ./.ci/travis/install.sh
script:
    - ./.ci/travis/run.sh
